### ISSUE TITLE
Images not showing up properly on my site. 

### ISSUE THREAD

**Issue by rasronin** [johnroper100/dropplets#321]
First of all, thank you very much for the great effort. I'm having on tiny problem though that is extremely annoying. The only way I can get images to show up in the post is to do this:

```
 ![ImageAltText](posts/somepic.png)
```

Instead of simply just writing:

```
  ![ImageAltText](somepic.png)
```

Now this wouldn't be an issue, except the later is the normal way of writing it in my Markdown Editor but I have to add posts in order to get it to work on the site.

Here is my .htaccess file for reference:

```
# Pretty Permalinks
RewriteRule ^(images)($|/) - [L]
RewriteCond %{REQUEST_URI} !^action=logout [NC]
RewriteCond %{REQUEST_URI} !^action=login [NC]
Options +FollowSymLinks -MultiViews
RewriteEngine on
RewriteBase /blog/
RewriteCond %{REQUEST_URI} !index\.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php?filename=posts/$1 [NC,QSA,L]
```

Also my blog is in a folder on the root called "blog". Can anyone please point me in the right direction.

**Comment by ayoubkhan558** [comment]
Just make sure image names and extension are in lower case. Don't use uppercase.
