### ISSUE TITLE
Cannot Edit Intro Text

### ISSUE THREAD

**Issue by ChristianK89** [johnroper100/dropplets#418]
Cant Change Intro Text

**Comment by semioticrobotic** [comment]
Can you please be a bit more descriptive? What specifically are you attempting to do? What are you expecting to happen when you do it? And what's happening instead?

**Comment by ChristianK89** [comment]
In Settings Panel there is an Option to edit Intro Text. If i would change this to something custom dropplets dont accept the change. Nothing is happening. If i change Meta it will work properly.

In Intro Text there is a default Text

 "In a flooded selection of overly complex solutions, Dropplets has been created in order to deliver a much needed alternative. There is something to be said about true simplicity in the design, development and management of a blog. By eliminating all of the unnecessary elements found in typical solutions, Dropplets can focus on pure design, typography and usability. Welcome to an easier way to blog." 

and i would change this

**Comment by ChristianK89** [comment]
helped me out editing text in config.php

**Comment by johnroper100** [comment]
ok, I'll take a look.

**Comment by johnroper100** [comment]
Ok, I will look into it.

**Comment by johnroper100** [comment]
I'm working on a rewrite so I'm going to close this for now.
