### ISSUE TITLE
PHP Notices and read more don't work

### ISSUE THREAD

**Issue by Innercode** [johnroper100/dropplets#420]
Hi,
First of all, thanks for dropplets. Exactly what I was looking for.

Then, on a fresh installation, I get the following PHP Notices:
```
[Fri Jul 28 13:32:28 2017] PHP Notice:  Undefined variable: author in /home/innercode/Code/dropplets/index.php on line 75
[Fri Jul 28 13:32:28 2017] PHP Notice:  Use of undefined constant IS_CATEGORY - assumed 'IS_CATEGORY' in /home/innercode/Code/dropplets/dropplets/functions.php on line 280
```

I'm running it on PHP 7.0.18

The same installation, happening to all templates and posts, the read more links don't work. It goes to the correct URL but shows the index page.

Thanks in advance!

**Comment by benlk** [comment]
> The same installation, happening to all templates and posts, the read more links don't work. It goes to the correct URL but shows the index page.

Are you using Apache or Ngnix?

The notices appear to be benign.
