### ISSUE TITLE
Install issue ?

### ISSUE THREAD

**Issue by yannickvdthoren** [johnroper100/dropplets#423]
Hey, 

When I install dropplets, it give me this result and I can do nothing with my website... Any idea ?

![capture d ecran 2017-09-22 a 11 43 36](https://user-images.githubusercontent.com/24243736/30738759-5fc23864-9f8b-11e7-89a3-2c2a4c53327a.png)
![capture d ecran 2017-09-22 a 11 43 54](https://user-images.githubusercontent.com/24243736/30738758-5fbfbcba-9f8b-11e7-94dd-ae662cfefbe4.png)

**Comment by johnroper100** [comment]
What template are you using?

**Comment by yannickvdthoren** [comment]
The basic one, I didn't change it. Thought it would not bug with this one...
Also, the website never stop sending me an e-mail to say that my website it created...

**Comment by johnroper100** [comment]
I'm working on a rewrite so I'm closing this for now.

**Comment by yannickvdthoren** [comment]
Do you need help on rewriting the code ? Maybe I have enough knowledge in HTML/CSS/JS to help :)

**Comment by johnroper100** [comment]
It would be great to have a little help! Currently I am trying to work the backend out, but I will share my mockups for the frontend HTML design soon.

**Comment by yannickvdthoren** [comment]
I'll be more than happy to help you, I always liked that project because it's really simple to setup and to use !

**Comment by johnroper100** [comment]
The goal of the rewrite, is to have the entire application contained in one PHP file. This should be even faster to setup and use.

**Comment by johnroper100** [comment]
Check the new readme in the 2.0 branch and the issue I created for information.
