### ISSUE TITLE
split() is deprecated in PHP5.3.0 and removed in 7.0 

### ISSUE THREAD

**Issue by cleary** [johnroper100/dropplets#424]
ref: http://php.net/manual/en/function.split.php

I've substituted str_split() verbatim and it seems to be working - I am no php developer, so the implications are lost on me.

**Comment by johnroper100** [comment]
Ok. I'l take a look at this.

**Comment by johnroper100** [comment]
Where is this in the code?

**Comment by cleary** [comment]
Ah sorry, index.php, approx line 342, get_twitter something function. Sorry
for lack of detail, working off my phone at the moment :P

**Comment by cleary** [comment]
apologies again, it *was* in dropplets/functions.php, but I'm not seeing it in current master - I need to update, apologies for the dud report!

`327-    // Get the cached profile image.
328-    $cache = IS_CATEGORY ? '.' : '';
329:    $array = str_split('/category/', $_SERVER['REQUEST_URI']);
330:    $array = str_split('/', $array[1]);
331-    if(count($array)!=1) $cache .= './.';
332-    $cache .= './cache/';`
