### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Torsten-K** [johnroper100/dropplets#426]
After the installation, nothing is shown but a blank page with HTTP ERROR 500. I tested on two different webhosters with PHP 5.6, 7.1 and 7.2.

**Comment by RyderMais** [comment]
Same...

**Comment by johnroper100** [comment]
I'll take a look at this, However, I am planning on a new rewritten version of Dropplets.

**Comment by semioticrobotic** [comment]
Great to hear, @johnroper100! Can you elaborate on your plans? And how can the community get involved?

**Comment by johnroper100** [comment]
My thought is a one-file rewrite with minimal setup to be even quicker than it is already.
