### ISSUE TITLE
Image + template

### ISSUE THREAD

**Issue by yannickvdthoren** [johnroper100/dropplets#428]
Hey !

I have installed the website and it works perfectly fine ! 

Can we have image ? 
> I tried with html tags, maybe markdown ?

**Found it !** (And how can I create a template for the website ?)
> Do you think it's possible to give each post his own css file ? This way, we should personalise every post, a bit like a paper magazine...

**Comment by johnroper100** [comment]
I'm glad that you like it so far! I just fixed a bug that didn't allow HTML tags to be used in post content, but they should work now. You just have to download index.php and upload the new version to your server. As for the custom CSS file for posts, I can add it, but I want to figure out how to do it in a way that is simple.

I am going to add a button that would be visible under HTTP://(your URL)/update/ that would update droplets to the latest version without you needing to do so manually.

**Comment by johnroper100** [comment]
I added a todo section in the readme

**Comment by johnroper100** [comment]
You can now add a custom stylesheet for posts, both globally and on a post-per-post level.

**Comment by johnroper100** [comment]
You can also go to http://(your URL)/update/ to update
