### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by untitled-sh** [johnroper100/dropplets#429]
Dear John, did you've tried it "online" too? Since I don't have a local PHP-IDE, I do use my own webserver with PHP Version 7.1.0 and Apache 2.0. The file is coded with UTF-8 BOM. I'm always getting followed Warning: Cannot modify header information - headers already sent by (output started at /.../index.php:3) in /.../index.php on line 260. I've checked already for Spaces etc. Any clue?

**Comment by johnroper100** [comment]
Can you try with the latest version?

**Comment by untitled-sh** [comment]
1st, thanks for your answer. I've already tried the latest version commit "_fb823a5  2 days ago_" Still I downloaded the latest commit again and tried it with the same result. Can you tell me, how is your env setup? What version of PHP are you using?

**Comment by johnroper100** [comment]
I'll have to check, but I'm testing with the default setup on my site ground web hosting which is at least 5 if not 7. Droplets should work with both. For development, I use the local run command (in the README) and I have Php 7.

**Comment by johnroper100** [comment]
Are you still having this issue?

**Comment by johnroper100** [comment]
I'll try and look more into this. For some reason, I can't reproduce this at all.

**Comment by untitled-sh** [comment]
It's actually not closed, since you still deliver raw html before the script triggers header()

Just to come along this error, I've cleared Line1,2 and of course the last. So therefore I could play a little with dropplets v2.0 beta.

**Comment by johnroper100** [comment]
I just published a fix where no html is sent before header, try it now.

**Comment by untitled-sh** [comment]
Issue is solved now. Thx
