### ISSUE TITLE
Does not work in sub directories

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/dropplets#430]
Currently Dropplets gets the url by checking the url:
`if ($URI_parts[1] and $URI_parts[1] == 'post')`

In this example, it checks if the item in array location `1` equals `post`. However, this poses a problem if Dropplets is in a sub folder on the server because if the url was `http://website.com/test/post` that if statement will never be true.

We need these checks to be based off the base directory.

**Comment by untitled-sh** [comment]
Would these examples be a good approach to solve the problem?

https://stackoverflow.com/questions/7395049/get-last-part-of-url-php

Sry, cannot really try yet.

**Comment by johnroper100** [comment]
That worked, and that part of the issue has been solved, but currently, the way to .htaccess is setup, it only works if the url is `http://webiste.com/test/index.php/setup` when it should be `http://webiste.com/test/setup`

**Comment by johnroper100** [comment]
The htaccess looks like:

```
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-l
	RewriteRule .* [L,QSA]
</IfModule>
```

**Comment by untitled-sh** [comment]
Dear John, I got a working master with followed .htaccess.

```
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-l
	RewriteRule ^(.*)$ index.php?/$1 [L,QSA]
</IfModule>
```

**Comment by johnroper100** [comment]
Ok, thanks! does this solve your other header issue as well?

**Comment by johnroper100** [comment]
This is back to not working, but only for the home page.

**Comment by johnroper100** [comment]
Fixed in latest commit

**Comment by untitled-sh** [comment]
Only issue I see for now is, that the _siteTitleLink_ is heading "back" to DOM an not subDIR.

BTW: Is there a special reason, why you make use of an right arrow and rotate it 90 degree?

**Comment by johnroper100** [comment]
I don't think there was a special reason for the arrow. I didn't do the style, I'll take a look. As for the link, I'm still working on it.
