### ISSUE TITLE
Post url

### ISSUE THREAD

**Issue by yannickvdthoren** [johnroper100/dropplets#433]
Hey,

Is it possible to have a more useful url for the blog post like url.com/blogTitle or with the date like this /2018-08-31-blogTitle ?

**Comment by johnroper100** [comment]
Thanks for the idea! I'll look into it.

**Comment by johnroper100** [comment]
Dropplets v2.0 now uses a format where for a given post, the url would be: `http://(yoururl)/posts/2019/01/14/post_name`
