### ISSUE TITLE
Html tags

### ISSUE THREAD

**Issue by yannickvdthoren** [johnroper100/dropplets#436]
Hey,

I have some problem adding html tags in my post. It make everything crash...

**Comment by johnroper100** [comment]
Can you share an example post text so I can try?

**Comment by johnroper100** [comment]
Markdown is preferred. So try with markdown and then style based on what is produced

**Comment by yannickvdthoren** [comment]
I want to create a post with the different style so basically something like this :

Here is an example for a code :

<code>
    //Here come the code
</code>

<quote>
For a bunch of hairless apes, we've actually managed to invent some pretty incredible things.
<span>- Ernest Cline, Ready Player One</span>
</quote>

And an hr !
<hr>

Let's see the list :
<ul>
<li>An element</li>
<li>An element</li>
<li>An element</li>
</ul>
<ol>
<li>An element</li>
<li>An element</li>
<li>An element</li>
</ol>

Ok ! I'll look at the markdown way of stuff ! ^^
