### ISSUE TITLE
URL to a single post page not work.

### ISSUE THREAD

**Issue by inercianet** [johnroper100/dropplets#437]
Hello, first of all congratulate you for your idea, I love it.

But I have a small problem:

I installed your script here: https://inercia.net/blog

But the URL to a single post page not work.

When i click in a post, the url nesting again and again:

Example: https://inercia.net/blog/posts/posts/posts/posts/posts/posts/1

I thought it could be a problem with the httacces (RewriteBase) but it did not work

Any idea?

Thank you

**Comment by johnroper100** [comment]
This has been fixed today.
