### ISSUE TITLE
Will Markdown return in 2.0?

### ISSUE THREAD

**Issue by briatte** [johnroper100/dropplets#438]
It seems that v2.0 is dropping support for just having plain `.md` files in `/posts`, and supports only posts written as a PHP file instead.

Is that decision permanent, or will it be again possible to use Dropplets as a Markdown-based engine?

**Comment by johnroper100** [comment]
You can use markdown, html, and plaintext to write your posts in v2.0 using the built-in editor, but there is no ability to upload plain md files for use as of this time. I can add it to the todo list though.

**Comment by briatte** [comment]
Thanks for your answer; that'd be great! I use Dropplets only through Markdown uploads, and while v2.0 looks great, I know that I will not use it until it supports drag-and-dropping posts like I do in v1.x.
