### ISSUE TITLE
Documentation website + Dropplets v1 question

### ISSUE THREAD

**Issue by briatte** [johnroper100/dropplets#444]
I'm still running Dropplets v1, and love it, but I could not find the online docs today.

I was looking for the definition of what goes on the second and fourth lines of the YAML header of posts:

```
# Title
- Author
- ?
- 2019-06-28
- Foo, Bar
- published
```

What goes on line 2 again?

And is it correct to have several tags (or categories?) on line 4?

**Comment by johnroper100** [comment]
Sorry, but I don't support v1 anymore.
