### ISSUE TITLE
Anyone using version 2.0 beta?

### ISSUE THREAD

**Issue by kkarthik23** [johnroper100/dropplets#445]
Looks like it doesn't use markdown files anymore and  content is stored in php files.

Looks simple and functional, though had some issues with markdown being rendered effectively as output.

For example code blocks didn't work in markdown whereas inline code formatting worked.

Looking for some feedback from others who have used this version.

**Comment by johnroper100** [comment]
I'll take a look at the code blocks issue.

**Comment by johnroper100** [comment]
It has been fixed
