### ISSUE TITLE
Apostrophe in post content causes error

### ISSUE THREAD

**Issue by jdalbey** [johnroper100/dropplets#446]
When I create a post that contains an apostrophe, the post won't appear and the following error is generated:

**Comment by jdalbey** [comment]
When I create a post that contains an apostrophe, the post won't appear and the following error is generated:PHP Parse error:  syntax error, unexpected 's' (T_STRING) in .../posts/2020/02/10/Second+post.php on line 3

**Comment by johnroper100** [comment]
I'll take a look.

**Comment by johnroper100** [comment]
Hi, this has been fixed!
